"""Create local image aliases to satisfy deck image paths.

This handles reprint-style deck entries where `set_code` (asset folder)
points to a starter set (e.g. ST11) but the card art already exists under
another set folder (e.g. OP02).

It reads `output/reports/deck_image_audit.json` (generated by
`tools/validate_deck_images.py`) and tries to copy an existing image into the
expected `assets/cards/<set_code>/<card_code>.(png|jpg|jpeg)` location.

Goal: eliminate "card backs" due to missing local assets without changing deck
JSON contents.
"""

from __future__ import annotations

import json
import os
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable


PROJECT_ROOT = Path(__file__).resolve().parents[1]
AUDIT_PATH = PROJECT_ROOT / "output" / "reports" / "deck_image_audit.json"
ASSETS_CARDS_DIR = PROJECT_ROOT / "assets" / "cards"
OUTPUT_IMAGES_DIR = PROJECT_ROOT / "output" / "images" / "cards"


IMAGE_EXTS = (".png", ".jpg", ".jpeg")


@dataclass(frozen=True)
class MissingItem:
    deck: str
    set_code: str
    card_code: str
    name: str | None = None


def _load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _iter_missing(audit: dict[str, Any]) -> Iterable[MissingItem]:
    for entry in audit.get("missing", []):
        yield MissingItem(
            deck=entry.get("deck", ""),
            set_code=entry.get("set_code", ""),
            card_code=entry.get("card_code", ""),
            name=entry.get("name"),
        )


def _set_prefix_from_code(code: str) -> str | None:
    if not code:
        return None
    if "-" not in code:
        return None
    return code.split("-", 1)[0]


def _find_card_object(deck_path: Path, set_code: str, card_code: str) -> dict[str, Any] | None:
    if not deck_path.exists():
        return None
    deck = _load_json(deck_path)
    for section in ("main", "don", "side", "extra"):
        cards = deck.get(section)
        if not isinstance(cards, list):
            continue
        for card in cards:
            if not isinstance(card, dict):
                continue
            if card.get("set_code") == set_code and card.get("card_code") == card_code:
                return card
    return None


def _existing_image_for(code: str) -> Path | None:
    """Find an existing image for a given card code in common locations."""

    prefix = _set_prefix_from_code(code)
    candidates: list[Path] = []

    if prefix:
        for ext in IMAGE_EXTS:
            candidates.append(ASSETS_CARDS_DIR / prefix / f"{code}{ext}")
            candidates.append(OUTPUT_IMAGES_DIR / prefix / f"{code}{ext}")
            # Some download layouts might be flat
            candidates.append(OUTPUT_IMAGES_DIR / f"{code}{ext}")

    # Also search by exact filename anywhere under output/images/cards (bounded-ish)
    for ext in IMAGE_EXTS:
        candidates.append(OUTPUT_IMAGES_DIR / f"{code}{ext}")

    for path in candidates:
        if path.exists():
            return path
    return None


def _copy_image(src: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)


def main() -> int:
    if not AUDIT_PATH.exists():
        raise SystemExit(f"Audit file not found: {AUDIT_PATH}")

    audit = _load_json(AUDIT_PATH)

    total = 0
    copied = 0
    skipped = 0
    failed = 0

    for item in _iter_missing(audit):
        # Only handle "image not found" cases; ignore other reasons.
        total += 1

        dest_dir = ASSETS_CARDS_DIR / item.set_code
        deck_path = (PROJECT_ROOT / item.deck).resolve()

        card_obj = _find_card_object(deck_path, item.set_code, item.card_code)
        card_id = (card_obj or {}).get("id")

        base_code_from_id: str | None = None
        if isinstance(card_id, str) and card_id:
            base_code_from_id = card_id.split("_", 1)[0]

        # Prefer the most specific art if it exists (e.g. P-041_p5), then fallback.
        source_code_candidates: list[str] = []
        if isinstance(card_id, str) and card_id:
            source_code_candidates.append(card_id)  # e.g. P-041_p5
        if base_code_from_id and base_code_from_id != item.card_code:
            source_code_candidates.append(base_code_from_id)  # e.g. P-041
        source_code_candidates.append(item.card_code)

        src: Path | None = None
        for source_code in source_code_candidates:
            src = _existing_image_for(source_code)
            if src is not None:
                break

        if src is None:
            failed += 1
            continue

        dest = dest_dir / f"{item.card_code}{src.suffix.lower()}"
        if dest.exists():
            skipped += 1
            continue

        try:
            _copy_image(src, dest)
            copied += 1
        except OSError:
            failed += 1

    print(
        json.dumps(
            {
                "audit": os.fspath(AUDIT_PATH),
                "total_missing_entries": total,
                "copied": copied,
                "skipped": skipped,
                "failed": failed,
            },
            indent=2,
        )
    )

    return 0 if failed == 0 else 2


if __name__ == "__main__":
    raise SystemExit(main())
